from __future__ import annotations

import copy
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path


DOCX_INPUT = Path(r"c:\Users\DELL\Downloads\f for finla.docx")
DOCX_OUTPUT = Path("FinX_Project_Report.docx")
NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
XML_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
ET.register_namespace("w", XML_NS)


def build_replacements() -> dict[int, str]:
    replacements: dict[int, str] = {
        1: "FINX - AN EXPENSE TRACKER AND PERSONAL FINANCE MANAGEMENT SYSTEM",
        13: "[ 1st Jan 2026 to 16th April 2026]",
        17: 'This is to certify that the project report submitted along with the project entitled "FinX - An Expense Tracker and Personal Finance Management System" has been carried out by Vadnagari Shubham Mehulkumar under my guidance in partial fulfilment for the degree of Bachelor of Engineering in Computer Engineering, 8th Semester of Gujarat Technological University, Ahmedabad during the academic year 2025-26.',
        26: 'We hereby declare that the project report submitted along with the project entitled "FinX - An Expense Tracker and Personal Finance Management System" in partial fulfilment for the degree of Bachelor of Engineering in Computer Engineering to Gujarat Technological University, Ahmedabad, is a bonafide record of original project work carried out by me under the supervision of Prof. Hitesh Rajput and that no part of this report has been directly copied from any students\' reports or taken from any other source without providing due reference.',
        32: "I would like to express my sincere gratitude to everyone who supported me throughout the development of FinX. I am especially thankful to my internal guide, Prof. Parth Dave, for his continuous encouragement, valuable feedback, and academic guidance during the planning, implementation, and documentation phases of this project.",
        33: "I am also grateful to all mentors, faculty members, and peers whose technical suggestions and discussions helped me refine the product vision, improve the architecture, and complete the project with greater clarity and confidence.",
        34: "Finally, I would like to thank my department, my friends, and the learning resources that supported me while building this full-stack finance management platform. Their support played an important role in the successful completion of this project.",
        39: 'During the development of "FinX", I worked on a full-stack expense tracker and personal finance management system built to help users monitor income, track expenses, manage savings, plan goals, split group expenses, and receive AI-assisted financial insights in one place.',
        40: "My core responsibilities included designing responsive frontend interfaces in React, building REST APIs with Node.js and Express, modelling data in MongoDB, and integrating secure authentication, notifications, chat, and analytics workflows for a modern finance application.",
        41: "FinX enables users to complete their profile, define their income source and preferred currency, record income and expense transactions, organize custom categories, monitor monthly trends on a dashboard, maintain a savings ledger, lock money into goals, and manage shared expenses with groups.",
        42: "The platform also includes real-time and smart features such as notifications, user-to-user messaging, attachment support, profile photo uploads, and AI-generated financial analysis using transaction and savings data to suggest actions, highlight risks, and support planning.",
        43: "By the end of the project, I had built a modular and scalable finance management application that strengthened my understanding of MERN-style architecture, API design, authentication, state management, real-time communication, and user-centred product design.",
        46: "Fig 1.1FinX Logo1",
        47: "Fig 2.1FinX Module Overview6",
        54: "Fig 5.2Dashboard Page23",
        55: "Fig 5.3Transactions Page24",
        56: "Fig 5.4Investments Page24",
        57: "Fig 5.5Savings Goals Page25",
        58: "Fig 5.6Login Page25",
        59: "Fig 5.7Profile Setup Page26",
        60: "Fig 5.8Group Expenses Page26",
        61: "Fig 5.9AI Insights Page28",
        62: "Fig 5.10Settings Page29",
        71: "IDEIntegrated Development Environment",
        72: "APIApplication Programming Interface",
        73: "JWTJSON Web Token",
        74: "HTMLHyper Text Markup Language",
        75: "CSSCascading Style Sheet",
        76: "JSJavaScript",
        77: "DBMSDatabase Management System",
        78: "AIArtificial Intelligence",
        79: "CRUDCreate Read Update Delete",
        80: "RESTRepresentational State Transfer",
        81: "UISUser Interface State",
        82: "UXUser Experience",
        83: "UIModern Interface Design",
        84: "WebSocketReal-Time Two-Way Communication",
        85: "MERNMongoDB Express React Node",
        149: "FinX is a personal finance management platform designed to help users understand, control, and improve their day-to-day financial activity. It combines expense tracking, income management, savings discipline, collaborative expense splitting, and AI-assisted analysis in a single web application.",
        150: "TRACK, SAVE & GROW",
        151: "The core idea behind FinX is to provide a structured digital workspace where financial actions are recorded clearly and converted into useful insights. The project focuses on simplicity, clarity, and practical decision support for users managing personal budgets and shared expenses.",
        154: "Different Services",
        155: "Personal finance dashboard",
        156: "Provides income, expense, savings, category, and trend summaries through cards and charts so users can quickly understand their monthly financial position.",
        157: "Transaction management",
        158: "Users can add, filter, and review income and expense transactions with notes, dates, categories, and optional attachments for better record keeping.",
        159: "Category management",
        160: "FinX supports both default and user-defined categories for income and expense records, enabling personalized financial organization.",
        161: "Savings and investment ledger",
        162: "The application tracks savings deposits and withdrawals, calculates available balance, and warns users when they try to save beyond the remaining monthly amount.",
        163: "Goal planning",
        164: "Users can create financial goals, move savings into locked goal funds, mark goals as completed, and monitor remaining target amounts over time.",
        165: "Group expense management",
        166: "FinX allows users to create groups, add members, record shared expenses, split amounts among participants, and manage settlement status.",
        167: "Notifications and chat",
        168: "The platform includes notifications for key actions and direct messaging support to improve collaboration between users involved in shared financial activity.",
        169: "AI financial insights",
        170: "AI-generated insight modules analyze transaction, savings, and goal data to surface recommendations, risk assessments, and future planning suggestions.",
        171: "Secure authentication",
        172: "JWT-based authentication, hashed passwords, route protection, and validated backend APIs keep user-specific financial data secure.",
        173: "Responsive interface design",
        174: "The frontend is designed for desktop and mobile screens using reusable UI primitives, gradient-driven visuals, and chart-based reporting components.",
        175: "Media support",
        176: "Profile photos and financial attachments are supported through upload flows so users can keep related visual records along with their data.",
        177: "Real-time collaboration",
        178: "Socket.io is used to support connected experiences such as messaging and room-based group communication flows.",
        179: "Scalable backend structure",
        180: "The backend follows a modular structure with models, controllers, routes, validators, and middleware to keep the codebase maintainable.",
        181: "Data-driven planning",
        182: "FinX transforms raw transactions into monthly trends, category breakdowns, savings summaries, and actionable analysis for everyday decision making.",
        191: "FinX Project Architecture",
        192: "FinX is organized as a full-stack web application with separate frontend and backend layers. The frontend manages user interaction and visualization, while the backend handles authentication, persistence, business rules, notifications, and AI integration.",
        193: "ALL MODULES",
        194: "Frontend Module",
        195: "Backend Module",
        196: "Database & Integration Module",
        197: "TECHNICAL SPECIFICATIONS IN PROJECT",
        198: "Frontend Module",
        199: "The frontend is built with React, TypeScript, Vite, Tailwind CSS, reusable UI components, and Recharts. It provides pages for dashboard analytics, transactions, investments, goals, groups, chat, AI insights, notifications, settings, login, signup, and profile setup.",
        200: "Backend Module",
        201: "The backend is built with Node.js, Express.js, and Mongoose. It exposes REST APIs for authentication, profile updates, transactions, categories, investments, wishlist goals, group expenses, notifications, chat, and AI insight generation. Socket.io is used for real-time communication support.",
        202: "SEQUENCE OF OPERATIONS",
        203: "Requirement Analysis & Feature Planning: The project started by identifying core finance workflows such as transaction logging, savings tracking, goal funding, and collaborative expense sharing.",
        204: "UI Development & API Implementation: After planning, responsive screens were created on the frontend while backend routes, controllers, middleware, and models were implemented to support each workflow.",
        205: "Testing, Integration & Refinement: Finally, data flows were tested end to end, validations were strengthened, charts and insights were refined, and the project report was prepared.",
        206: "PRODUCT STAGES",
        207: "Fig 2.1 FinX Module Overview",
        212: "FinX - Expense Tracker and Personal Finance Management System",
        214: "The aim of FinX is to build a user-centric finance management platform that helps individuals track income and expenses, maintain savings discipline, plan financial goals, collaborate on shared spending, and receive actionable insights from their financial data through a clean and responsive interface.",
        216: "Self-driven academic project",
        218: "Web Application",
        221: "Visual Studio Code",
        223: "React JS, TypeScript, Node JS, Express JS, MongoDB, Tailwind CSS",
        225: "Axios, Recharts, Socket.io, Cloudinary, Gemini API, Sonner, Radix UI",
        227: "4 Months (January 2026 to April 2026)",
        229: "The purpose of FinX is to provide a single platform where users can manage everyday financial records, study spending behaviour, preserve savings, and plan future goals without relying on scattered tools or manual calculations.",
        230: "It also supports shared finance scenarios by letting users create groups, add members, split expenses, monitor balances, communicate through chat, and receive notifications for important events.",
        231: "• Facilitate structured income and expense tracking through categorized transaction records.",
        232: "• Provide secure authentication and user-specific access to private financial data.",
        233: "• Offer meaningful analytics through dashboards, category breakdowns, and monthly trend charts.",
        234: "• Enable savings management, goal locking, and AI-based planning suggestions for better decision making.",
        235: "• Support collaborative expense tracking with groups, balance sheets, notifications, and messaging.",
        237: "The objective of the application is to deliver a modern finance management solution that combines core bookkeeping, planning, and insight generation in a single responsive web platform.",
        238: "In addition, the system is designed to help users maintain cleaner financial records, make informed choices from charts and AI recommendations, and manage both personal and shared expenses more efficiently.",
        240: "The scope of FinX includes personal expense tracking, income management, category management, savings and withdrawals, savings goals, group expense sharing, notifications, direct chat, and AI-powered financial analysis.",
        241: "It is intended for users who want a practical web-based solution for recording transactions, reviewing monthly performance, organizing savings, and collaborating with others on shared costs through an accessible interface.",
        242: "Functional Scope:",
        243: "User Authentication & Profile Management:",
        244: "Secure sign-up and login with JWT-based authentication. Users can complete profile setup with income source, monthly income, preferred currency, and phone number, and can later update account settings and profile photo.",
        245: "Core Finance Management Features:",
        246: "Users can add transactions, organize categories, record savings deposits and withdrawals, create financial goals, fund goals from savings, and review monthly summaries. Group creators can add members and manage shared expenses and settlements.",
        247: "Insight & Collaboration Features:",
        248: "Dashboard analytics, notifications, direct messaging, and AI-generated financial insights provide users with contextual awareness, future planning guidance, and smoother group coordination.",
        249: "Future Scope:",
        250: "Budget automation, recurring transactions, downloadable reports, enhanced AI coaching, and mobile app extensions can be added in future versions.",
        252: "React JS & TypeScript:",
        253: "The frontend uses React components, hooks, TypeScript-based structure, reusable UI primitives, and chart libraries to build an interactive and responsive user experience.",
        254: "MongoDB:",
        255: "MongoDB is used to persist users, transactions, categories, savings entries, goals, groups, group expenses, notifications, and chat messages in a document-oriented structure.",
        256: "Node JS & Express JS:",
        257: "The backend uses Express routes, controllers, middleware, validators, and Mongoose models to implement secure APIs and finance-specific business rules.",
        258: "Third-party libraries and APIs:",
        259: "Cloudinary supports uploads, Socket.io supports real-time communication, Axios handles HTTP communication, and Gemini-based generation is used for AI financial insight responses.",
        264: "According to the project requirements, scrum methodology was chosen to organize iterative development, validate features continuously, and refine the product based on implementation feedback.",
        271: "Roles and Responsibilities",
        272: "Product Planning",
        273: "The project work included analysing personal finance use cases, prioritizing user journeys, identifying necessary data entities, and defining how dashboards, savings, goals, and group workflows should behave.",
        274: "Design and Development",
        275: "The development responsibility covered frontend screen building, reusable component composition, backend API creation, MongoDB data modelling, authentication handling, and integration between all product modules.",
        276: "Testing and Documentation",
        277: "The final phase involved checking end-to-end flows, validating user input, refining error handling and notifications, and documenting the complete system in a structured report.",
        278: "Group Dependencies",
        279: "In FinX, modules depend on one another through shared business data. Authentication controls access, transactions feed analytics, investments affect savings availability, goals lock savings, and groups, notifications, chat, and AI insights all depend on accurate core financial records.",
        280: "Pooled interdependence",
        281: "Independent modules such as dashboard cards, notifications, and settings use common user and finance data to present different views of the same system state.",
        282: "Sequential interdependence",
        283: "A user typically completes profile setup before recording transactions, records transactions before studying insights, and builds savings before funding goals or managing shared settlements.",
        284: "Reciprocal interdependence",
        285: "Transactions, investments, goals, and AI insights continuously influence each other because changes in one area affect balances, recommendations, and visible summaries elsewhere in the application.",
        286: "Comprehensive interdependence",
        287: "For the complete experience to work correctly, frontend pages, backend APIs, database models, validations, and optional integrations such as sockets and AI generation must remain aligned.",
        303: "January",
        304: "February",
        305: "March",
        306: "April",
        307: "Requirement Analysis",
        308: "UI/UX Design",
        309: "API and Data Modelling",
        310: "Frontend Development",
        311: "Integration and Testing",
        312: "Documentation",
        313: "Final Review",
        317: "Currently, many people use spreadsheets, note-taking apps, or isolated finance apps to monitor money. These approaches often track only one part of the problem, such as expenses alone, without connecting spending, savings, goals, shared expenses, and insight generation in a unified experience.",
        318: "Existing systems may provide budgeting or expense logging, but they frequently lack flexible category control, collaborative settlement workflows, real-time interaction, or deeper financial guidance from the accumulated data.",
        319: "• Financial records are often fragmented across multiple tools.• Shared expense settlement is usually handled outside the main tracker.• Many tools provide static summaries but limited actionable analysis.• Personalization and profile-based finance context are often missing.",
        320: "FinX addresses these gaps by combining tracking, planning, collaboration, and insight generation in one modular web application with secure user-specific workflows.",
        322: "1. Fragmented Record Keeping",
        323: "• Users often manage expenses, savings, and shared payments in separate tools.• This makes it difficult to maintain a single source of truth for financial activity.",
        324: "2. Limited Financial Context",
        325: "• Many systems display totals but do not relate transactions to goals, savings balance, or future planning.• This reduces the usefulness of the recorded data.",
        326: "3. Weak Collaboration Support",
        327: "• Traditional personal trackers rarely support groups, member balances, settlement tracking, or communication around shared expenses.",
        328: "4. Low Personalization",
        329: "• Users may not be able to define their own finance categories, preferred currency, or profile-specific budgeting context.",
        330: "5. Limited Smart Assistance",
        331: "• Most basic trackers do not convert financial history into advice, warnings, or planning suggestions that help users take action.",
        332: "• FinX improves this by connecting structured data with dashboards and AI-generated guidance.",
        334: "Below are the technical requirements to develop the FinX personal finance management application.",
        335: "Software Requirements",
        336: "Operating System: Windows 10/11, Linux, or macOS",
        337: "IDE: Visual Studio Code",
        338: "Application Server: Node.js runtime with Express.js server",
        339: "Frameworks and APIs: React, TypeScript, Vite, Tailwind CSS, Express.js, Socket.io, Recharts",
        340: "Database: MongoDB",
        341: "Front End: HTML5, CSS3, JavaScript, TypeScript",
        342: "Web Service: RESTful APIs with optional real-time socket communication",
        343: "Browser: Chrome, Edge, or Firefox",
        344: "Deployment Support: Localhost or cloud-hosted web environment",
        345: "Hardware Requirements",
        346: "Processor: Intel Core i5 / i7 or equivalent",
        347: "Processor speed: 2.4 GHz or higher",
        348: "RAM: 8 GB or above",
        352: "Actors:",
        353: "The main actors of the system are Registered User, Group Member, and the System Services layer.",
        354: "Use cases:",
        355: "I identified a set of use cases based on the major workflows implemented in FinX.",
        356: "• Register Account – Users create an account using email and password.",
        357: "• Login – Users authenticate and access protected application routes.",
        358: "• Complete Profile – Users define income source, monthly income, preferred currency, and contact details.",
        359: "• Manage Categories – Users create, update, and delete finance categories.",
        360: "• Add Transaction – Users record income and expenses with date, notes, and category information.",
        361: "• View Dashboard – Users review summaries, monthly trends, and category-wise breakdowns.",
        362: "• Manage Savings – Users add or withdraw savings entries and track available balance.",
        363: "• Create Goals – Users define target amounts and due dates for financial goals.",
        364: "• Fund Goals – Users move money from savings into locked goal allocations.",
        365: "• Manage Groups – Users create groups, add members, and review group details.",
        366: "• Add Shared Expense – Group creators record expenses and split them across members.",
        367: "• Settle Balance – Group expenses can be settled member by member and reflected in the balance sheet.",
        368: "• Read Notifications – Users view, mark, and clear actionable notifications.",
        369: "• Chat with Users – Users send direct messages to communicate around financial activities.",
        370: "• Generate AI Insights – The system analyses financial data and returns personalized recommendations.",
        371: "• Update Settings – Users update their profile, password, preferences, and avatar.",
        376: "FEATURE OF NEW SYSTEM",
        377: "User Authentication & Authorization",
        378: "Sign Up – New users can register with their email and password.",
        379: "Login – Users can log in using their credentials and access their personal finance workspace.",
        380: "Protected Routes – Users must be authenticated to access finance records, goals, groups, and settings.",
        381: "Logout – Users can securely log out and clear the active session.",
        382: "Finance Data Management (CRUD)",
        383: "1. Read Finance Records",
        384: "• Users can review transactions, savings entries, goals, categories, notifications, and shared expense details from dedicated pages and dashboard cards.",
        385: "2. Create Records",
        386: "• Users can create transactions, categories, savings entries, goals, groups, chat messages, and shared group expenses through guided forms and validations.",
        387: "3. Edit Records",
        388: "• Users can update investments, categories, profile details, settings, and certain group-related records depending on ownership and permissions.",
        389: "4.Delete Records",
        390: "• Users can remove categories, goals, savings entries, notifications, chat content, groups, and selected finance records where allowed by the system.",
        391: "5. Analytics and Planning",
        392: "• The dashboard presents monthly trends, category breakdowns, savings summaries, and balance information. The AI module adds recommendations, projected savings, and risk assessment outputs.",
        393: "6. Collaboration",
        394: "• Group members can participate in shared expense workflows, while notifications and chat help users coordinate changes and settlements.",
        395: "7. User-Specific Experience",
        396: "• Each user has a personalized dashboard, profile, preferred currency, custom categories, financial goals, and notifications derived from their own data and group participation.",
        397: "Third-Party Libraries & Enhancements",
        398: "React Router – Handles navigation between pages.",
        399: "Context API – Manages authentication and shared finance state.",
        400: "Sonner / Axios / Recharts / Socket.io – Support notifications, API communication, analytics visualization, and real-time features.",
        411: "The system design of FinX focuses on modularity, separation of concerns, and reusable user flows. The application is divided into independently manageable frontend pages, shared UI components, backend routes, controllers, middleware, and database models so that product features can evolve without tightly coupling every layer.",
        413: "MongoDB is used to store user accounts, transactions, categories, savings records, goals, groups, group expenses, notifications, and messages. The schema design follows document-based modelling, which fits the project well because financial entities vary in shape and often contain nested or user-specific data.",
        414: "Hence, the core collections identified to achieve the desired functionality are User, Transaction, Investment, Wishlist Goal, Group, Category, Group Expense, Notification, and Message.",
        678: "When a user registers with the application, their profile information is stored in the User collection. Once authenticated, the user can complete profile setup and begin recording transactions, which are then used to generate dashboard analytics and AI insight summaries.",
        679: "User-created categories help organize future records. Savings entries update the investment summary, while goals lock part of the available savings into targeted financial objectives with measurable progress.",
        680: "When a user creates a group and adds members, shared expenses are saved in the Group Expense collection. Settlement states and group balances are derived from the recorded splits and reflected back to the user interface.",
        681: "Notifications and chat messages are stored separately so the system can support collaboration, unread indicators, and communication around finance actions without affecting the integrity of the underlying transaction records.",
        683: "Fig 5.1 : Flow chart of FinX Project",
        685: "Dashboard Page",
        686: "Login or Register Page",
        687: "Profile Setup Page",
        688: "Transactions Page",
        689: "Investments Page",
        690: "Savings Goals Page",
        691: "Group Expenses Page",
        692: "Group Detail Page",
        693: "AI Insights Page",
        694: "Settings Page",
        697: "Visual Studio Code",
        698: "Visual Studio Code is the primary integrated development environment used to build FinX. It provides fast editing, debugging, extension support, Git integration, terminal access, and a productive setup for both frontend and backend development workflows.",
        699: "Debugging and validation support",
        700: "The editor and browser-based tools were used to inspect UI issues, verify API data, monitor state transitions, and debug route-level or validation-related problems during implementation.",
        701: "Git commands built-in",
        702: "Version control support helped maintain the project structure, track iterative changes, and organize feature development across frontend and backend modules.",
        703: "FinX is a web-based finance management application that improves the way users record, understand, and plan their money. It provides a unified platform where users can manage personal transactions, savings, goals, group expenses, and insights from one dashboard-driven experience.",
        704: "The application is accessible across desktop and mobile devices through a responsive interface and offers a flexible environment for both personal finance use cases and collaborative expense tracking scenarios.",
        705: "The modules implemented in the FinX system are:• Authentication & Profile• Dashboard & Analytics• Transactions & Categories• Savings & Goals• Groups & Chat• Notifications & AI Insights",
        706: "6.2 Core Modules",
        707: "The core modules provide the main finance workflows required by the system.",
        708: "• Users can sign up, log in, complete profile setup, and manage settings such as password, currency, and profile photo.",
        709: "• Users can add, filter, and review income and expense transactions with categories, notes, and dates.",
        710: "• Users can manage savings deposits and withdrawals while viewing available balance, current month summary, and trend charts.",
        711: "• Users can create goals, allocate savings toward them, and track completion progress.",
        712: "• Users can create groups, add members, record shared expenses, and settle balances with collaborators.",
        713: "6.3 Intelligence & Collaboration",
        714: "FinX also includes collaborative and intelligent support modules.",
        715: "• Notifications keep users aware of important actions such as group events or updates that affect their finance workflow.",
        716: "• Chat allows users to send and review direct messages, improving coordination around shared expenses and planning.",
        717: "• The dashboard aggregates financial data into visual summaries for income, expenses, net balance, category breakdowns, and trend analysis.",
        718: "• The AI module generates comprehensive insights, projections, risks, and practical recommendations from transaction, goal, and savings data.",
        719: "• Secure backend validation, authentication middleware, and structured data models ensure that each user interacts only with authorized records.",
        720: "• The platform remains extensible so future modules such as recurring budgets, exports, or mobile support can be introduced without major restructuring.",
    }

    replacements.update(
        {
            723: "Testing is the process of executing a program with the intent of finding bugs and verifying that implemented features meet expected behaviour. In FinX, testing was performed across UI flows, backend validations, and end-to-end data interactions so the financial records and collaborative features remained dependable.",
            725: "Unit testing: Unit-level checking was used for isolated logic such as calculations, validation rules, and smaller UI behaviours.",
            726: "Integration testing: Connected modules such as authentication, transactions, dashboard summaries, investments, goals, and groups were tested together to verify correct API and state interactions.",
            727: "System testing: The complete system was tested as a working finance application to ensure that major user journeys behaved correctly from login to data review.",
            728: "Regression testing: After feature changes, core workflows such as login, transaction creation, savings updates, and group actions were rechecked to make sure earlier functionality still worked.",
            729: "Acceptance testing: Final behaviour was reviewed against project objectives to confirm that the system supports real personal finance management use cases.",
            730: "Following these levels of testing, the FinX application was reviewed module by module and then validated through realistic end-to-end workflows covering both personal and collaborative finance features.",
            732: "A test case is a set of rules or conditions used to verify whether a feature behaves according to the defined requirement. In FinX, test cases were created for authentication, finance management, planning, group collaboration, and insight generation workflows.",
            733: "I designed and executed representative test cases to check whether the system met the functional requirements implemented in the project.",
            734: "Below are the test cases for the FinX web application.",
            811: "The additional navigation-oriented test cases for the web application are as follows.",
            812: "Test Objectives: Navigation from Login screen to Dashboard screen",
            817: "The user is currently on the Login screen",
            818: "User enters valid credentials and clicks on login button",
            819: "Directs to Dashboard screen",
            821: "Table 2-Test Case for navigation to Dashboard screen",
            822: "Test Objectives: Navigation from Dashboard screen to Transactions screen",
            827: "The user is currently on the Dashboard screen",
            828: "User clicks on the Transactions option from the sidebar",
            829: "Directs to Transactions screen",
            831: "Table 3-Test Case for navigation to Transactions screen",
            832: "Test Objectives: Successfully creates a shared group expense",
            837: "The user is currently on the Group Detail page",
            838: "User enters expense details, selects members, and submits the form",
            839: "Prompts a message as “Group expense added successfully”",
            841: "Table 4-Test Case for shared group expense flow",
            842: "Test Objectives: User checks unread notifications",
            847: "The user is currently on the Dashboard page",
            848: "User clicks on the Notifications section",
            849: "Lists the unread and recent notifications for the user",
            851: "Table 5-Test Case for listing notifications",
            854: "Throughout the development of FinX, I gained practical experience in designing a product around real financial workflows instead of isolated demo screens. The project required me to think about data accuracy, user permissions, collaboration rules, and the clarity of financial insights presented on the interface.",
            855: "The project strengthened my understanding of React, TypeScript, Node.js, Express.js, MongoDB, authentication, reusable UI architecture, and finance-specific business logic.",
            856: "It also improved my ability to work with modular backend design, chart-based data visualization, and progressive feature refinement using an iterative development approach.",
            857: "I developed a better understanding of controller-based APIs, Mongoose data modelling, and how interconnected modules should share state safely.",
            858: "Tailwind CSS, reusable components, and dashboard design patterns were used extensively to keep the interface consistent and responsive.",
            859: "The project work was implemented feature by feature with continuous review and refinement.",
            860: "The final report documents the design choices, implementation details, and outcomes of the completed system.",
            862: "Problem Encountered:",
            863: "Maintaining consistency across transactions, savings, goals, and shared expense modules required careful business rules so one action did not produce incorrect balances elsewhere in the system.",
            864: "Possible Solutions: Strengthen centralized validation and summary calculations, add more automated tests for linked finance flows, and further separate domain logic into reusable service layers for easier maintenance.",
            865: "Another challenge was presenting complex financial data in a clean and user-friendly way without overwhelming the user.",
            866: "Possible Solutions: Continue refining chart presentation, progressive disclosure, empty states, and AI summaries so that advanced information remains understandable.",
            868: "January 20, 2026",
            869: "March 05, 2026",
            870: "April 16, 2026",
            872: "The current version does not yet include recurring budgets, bank integrations, or downloadable financial reports.",
            873: "Some features depend on accurate manual data entry, so insight quality improves only when users maintain complete records.",
            874: "Advanced automated testing and production deployment configurations can still be expanded for a more enterprise-ready release.",
            876: "Introduce recurring transactions, budget envelopes, and monthly plan automation.",
            877: "Expand AI assistance with richer coaching, anomaly detection, and smarter financial forecasting.",
            878: "Add exportable reports, stronger audit trails, and broader collaboration features for shared household or team finance management.",
            880: "FinX serves as a modern and practical expense tracker and personal finance management system that connects daily record keeping with meaningful analysis. By using React, TypeScript, Node.js, Express.js, MongoDB, and supporting libraries, the platform delivers a responsive, scalable, and feature-rich experience for users who want to manage both personal and shared finances in one place.",
            881: "The application meets the major functional goals defined during planning by providing secure authentication, transaction management, savings control, goal funding, group expense handling, notifications, chat, and AI-generated insights. Through this project, I gained strong hands-on experience in full-stack development and improved my ability to build modular, data-driven applications that solve real user problems.",
            883: "Web Siteshttps://react.dev https://nodejs.org https://expressjs.com https://www.mongodb.com https://mongoosejs.com https://socket.io https://recharts.org https://ai.google.dev",
        }
    )

    user_table = [
        "USER TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "name",
        "String",
        "No",
        "Full name of the user",
        "email",
        "String",
        "No",
        "Required + Unique",
        "passwordHash",
        "String",
        "No",
        "Hashed with bcryptjs",
        "monthlyIncome",
        "Number",
        "Yes",
        "Monthly income baseline",
        "preferredCurrency",
        "String",
        "No",
        "User display currency",
        "createdAt",
        "Date",
        "No",
        "Auto timestamp",
    ]
    for idx, value in zip(range(416, 449), user_table):
        replacements[idx] = value

    transaction_table = [
        "TRANSACTION TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "userId",
        "ObjectId",
        "No",
        "Reference to User",
        "amount",
        "Number",
        "No",
        "Income or expense amount",
        "type",
        "Enum",
        "No",
        "income / expense",
        "categoryId",
        "String",
        "No",
        "Category reference",
        "date",
        "Date",
        "No",
        "Transaction date",
        "notes",
        "String",
        "Yes",
        "Optional notes",
        "attachmentUrl",
        "String",
        "Yes",
        "Uploaded attachment URL",
        "createdAt",
        "Date",
        "No",
        "Creation timestamp",
        "__v",
        "Number",
        "Yes",
        "MongoDB version key",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    for idx, value in zip(range(449, 502), transaction_table):
        replacements[idx] = value

    investment_table = [
        "INVESTMENT TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "userId",
        "ObjectId",
        "No",
        "Reference to User",
        "entryType",
        "Enum",
        "No",
        "deposit / withdrawal",
        "name",
        "String",
        "No",
        "Entry title",
        "amount",
        "Number",
        "Yes",
        "Saved or used amount",
        "durationMonths",
        "Number",
        "Yes",
        "Duration metadata",
        "date",
        "Date",
        "No",
        "Entry date",
        "notes",
        "String",
        "Yes",
        "Optional remarks",
        "createdAt",
        "Date",
        "No",
        "Creation timestamp",
    ]
    for idx, value in zip(range(502, 543), investment_table):
        replacements[idx] = value

    goal_table = [
        "WISHLIST GOAL TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "userId",
        "ObjectId",
        "No",
        "Reference to User",
        "itemName",
        "String",
        "No",
        "Goal name",
        "targetAmount",
        "Number",
        "No",
        "Target to achieve",
        "savedAmount",
        "Number",
        "No",
        "Amount locked for goal",
        "deadline",
        "Date",
        "Yes",
        "Optional due date",
        "status",
        "Enum",
        "No",
        "active / completed",
        "completedAt",
        "Date",
        "Yes",
        "Completion date",
        "createdAt",
        "Date",
        "No",
        "Creation timestamp",
        "__v",
        "Number",
        "Yes",
        "MongoDB version key",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    for idx, value in zip(range(543, 604), goal_table):
        replacements[idx] = value

    group_table = [
        "GROUP TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "name",
        "String",
        "No",
        "Group name",
        "createdBy",
        "ObjectId",
        "No",
        "Creator reference",
        "members",
        "Array<ObjectId>",
        "No",
        "Group members",
        "createdAt",
        "Date",
        "No",
        "Creation timestamp",
        "__v",
        "Number",
        "Yes",
        "MongoDB version key",
    ]
    for idx, value in zip(range(604, 633), group_table):
        replacements[idx] = value

    category_table = [
        "CATEGORY / NOTIFICATION TABLE",
        "Field Name",
        "Data Type",
        "Nullable",
        "Comments",
        "_id",
        "ObjectId",
        "No",
        "Primary Key",
        "userId",
        "ObjectId",
        "Yes",
        "Null for default category",
        "name / title",
        "String",
        "No",
        "Label displayed to user",
        "type",
        "String",
        "No",
        "income, expense, info, group, etc.",
        "color / read",
        "Mixed",
        "Yes",
        "Display metadata or status",
        "message / data",
        "Mixed",
        "Yes",
        "Notification content or payload",
        "createdAt",
        "Date",
        "No",
        "Creation timestamp",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    for idx, value in zip(range(633, 678), category_table):
        replacements[idx] = value

    test_rows = [
        ("AUTH", "Provide valid signup details", "User account created successfully", "PASS"),
        ("AUTH", "Enter invalid login credentials", "Error message displayed", "PASS"),
        ("PROFILE", "Complete profile setup form", "Profile data saved and dashboard opened", "PASS"),
        ("TRANSACTION", "Add income transaction with valid data", "Transaction saved successfully", "PASS"),
        ("TRANSACTION", "Apply category and date filters", "Filtered transactions displayed correctly", "PASS"),
        ("CATEGORY", "Create custom expense category", "Category added successfully", "PASS"),
        ("INVESTMENT", "Add savings deposit", "Savings summary updated correctly", "PASS"),
        ("INVESTMENT", "Withdraw available savings", "Savings usage recorded successfully", "PASS"),
        ("GOAL", "Create new savings goal", "Goal created and shown in goals list", "PASS"),
        ("GOAL", "Fund goal from available savings", "Locked goal amount updated", "PASS"),
        ("GROUP", "Create a new expense group", "Group created and listed", "PASS"),
        ("GROUP", "Add member using email", "Member added to group successfully", "PASS"),
        ("GROUP", "Create shared expense in group", "Expense stored and split among members", "PASS"),
        ("GROUP", "Settle a member share", "Settlement state updated", "PASS"),
        ("CHAT", "Send direct message to another user", "Message delivered and stored", "PASS"),
        ("NOTIFICATION", "Mark notification as read", "Unread count updated", "PASS"),
        ("AI", "Generate comprehensive insights", "Insight cards and recommendations displayed", "PASS"),
        ("SETTINGS", "Save updated preferences", "Profile and settings saved successfully", "PASS"),
    ]
    cursor = 739
    for row in test_rows:
        for cell in row:
            replacements[cursor] = cell
            cursor += 1

    return replacements


def collect_non_empty_paragraphs(root: ET.Element) -> list[ET.Element]:
    paragraphs: list[ET.Element] = []
    for p in root.findall(".//w:p", NS):
        texts = [t.text or "" for t in p.findall(".//w:t", NS)]
        if "".join(texts).strip():
            paragraphs.append(p)
    return paragraphs


def set_paragraph_text(paragraph: ET.Element, text: str) -> None:
    text_nodes = paragraph.findall(".//w:t", NS)
    if text_nodes:
        text_nodes[0].text = text
        for node in text_nodes[1:]:
            node.text = ""
        return

    run = ET.SubElement(paragraph, f"{{{XML_NS}}}r")
    t = ET.SubElement(run, f"{{{XML_NS}}}t")
    t.text = text


def main() -> None:
    replacements = build_replacements()

    with zipfile.ZipFile(DOCX_INPUT, "r") as zin:
        document_xml = zin.read("word/document.xml")
        root = ET.fromstring(document_xml)
        paragraphs = collect_non_empty_paragraphs(root)

        for index, new_text in replacements.items():
            if 1 <= index <= len(paragraphs):
                set_paragraph_text(paragraphs[index - 1], new_text)

        updated_document_xml = ET.tostring(root, encoding="utf-8", xml_declaration=True)

        with zipfile.ZipFile(DOCX_OUTPUT, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = updated_document_xml if item.filename == "word/document.xml" else zin.read(item.filename)
                cloned = copy.copy(item)
                zout.writestr(cloned, data)

    print(DOCX_OUTPUT.resolve())


if __name__ == "__main__":
    main()
